Bugfixes
PlanBCode/mapmind pull request #1
Opened 2021-02-10 10:25 UTC by pierstitus

fix source and sink images, make it work on nginx and make country links work on other domains

2021-02-11 22:50 UTC, giplt requested changes
I believe changing the name for the map manipulation flag shouldn't be in this commit.

2021-02-11 22:50 UTC, giplt approved these changes

2021-02-11 22:53 UTC, giplt approved these changes

2021-02-11 22:55 UTC, giplt approved these changes

2021-02-12 08:19 UTC, pierstitus commented
the gManipulate variable was named ahnManipulate everywhere else, so probably it was an accidental typo in an earlier change. Changing it to dtmManipulate or so makes sense though.

2021-02-12 09:26 UTC, giplt commented
Shoot, I misread and thought proposed change was from ahn to g prefix.

2021-02-12 09:28 UTC, merged